services:
  postgres-db:
    container_name: secureauth-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: secureauth
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
